export const QA_ORGANISATION = {
  code: "cookieworks-manufacturing",
  name: "CookieWorks Manufacturing",
  primarySiteName: "Bodmin Cookie Factory",
} as const;

export const QA_ORGANISATION_CODE = QA_ORGANISATION.code;

export const QA_USERS = {
  admin: {
    id: "b0000000-0000-0000-0000-000000000001",
    email: "admin@cookieworks.local",
    password: "Admin@CookieWorks-QA-2026!",
    displayName: "CookieWorks Admin",
  },
  ciManager: {
    id: "b0000000-0000-0000-0000-000000000002",
    email: "ci-manager@cookieworks.local",
    password: "CiManager@CookieWorks-QA-2026!",
    displayName: "CookieWorks CI Manager",
  },
  productionManager: {
    id: "b0000000-0000-0000-0000-000000000003",
    email: "production-manager@cookieworks.local",
    password: "ProductionMgr@CookieWorks-QA-2026!",
    displayName: "CookieWorks Production Manager",
  },
  teamLeader: {
    id: "b0000000-0000-0000-0000-000000000004",
    email: "team-leader@cookieworks.local",
    password: "TeamLeader@CookieWorks-QA-2026!",
    displayName: "CookieWorks Team Leader",
  },
  operator: {
    id: "b0000000-0000-0000-0000-000000000005",
    email: "operator@cookieworks.local",
    password: "Operator@CookieWorks-QA-2026!",
    displayName: "CookieWorks Operator",
  },
  assessor: {
    id: "b0000000-0000-0000-0000-000000000006",
    email: "assessor@cookieworks.local",
    password: "Assessor@CookieWorks-QA-2026!",
    displayName: "CookieWorks Assessor",
  },
  finance: {
    id: "b0000000-0000-0000-0000-000000000007",
    email: "finance@cookieworks.local",
    password: "Finance@CookieWorks-QA-2026!",
    displayName: "CookieWorks Finance",
  },
} as const;

export const QA_USER_IDS: string[] = Object.values(QA_USERS).map(
  (user) => user.id,
);

export const QA_UNITS = [
  {
    key: "bodmin-cookie-factory",
    code: "bodmin-cookie-factory",
    name: "Bodmin Cookie Factory",
    type: "plant",
    parentKey: null,
  },
  {
    key: "operations",
    code: "operations",
    name: "Operations",
    type: "department",
    parentKey: "bodmin-cookie-factory",
  },
  {
    key: "mixing-preparation",
    code: "mixing-preparation",
    name: "Mixing & Preparation",
    type: "area",
    parentKey: "operations",
  },
  {
    key: "baking",
    code: "baking",
    name: "Baking",
    type: "area",
    parentKey: "operations",
  },
  {
    key: "decorating",
    code: "decorating",
    name: "Decorating",
    type: "area",
    parentKey: "operations",
  },
  {
    key: "packing",
    code: "packing",
    name: "Packing",
    type: "area",
    parentKey: "operations",
  },
  {
    key: "quality",
    code: "quality",
    name: "Quality",
    type: "department",
    parentKey: "bodmin-cookie-factory",
  },
  {
    key: "engineering",
    code: "engineering",
    name: "Engineering",
    type: "department",
    parentKey: "bodmin-cookie-factory",
  },
  {
    key: "warehouse",
    code: "warehouse",
    name: "Warehouse",
    type: "department",
    parentKey: "bodmin-cookie-factory",
  },
  {
    key: "continuous-improvement",
    code: "continuous-improvement",
    name: "Continuous Improvement",
    type: "department",
    parentKey: "bodmin-cookie-factory",
  },
] as const;

export const QA_ROLES = {
  ciManager: {
    canonicalName: "ci-manager",
    displayName: "CI / Operational Excellence Manager",
    description:
      "Organisation-wide continuous improvement and maturity configuration.",
    scopeType: "organisation" as const,
    scopeUnitKey: null,
    permissions: [
      "hierarchy.read",
      "memberships.read",
      "maturity.read",
      "maturity.models.manage",
      "maturity.assess.formal",
      "maturity.review",
      "maturity.approve",
      "maturity.results.publish",
      "five_s.read",
      "five_s.standards.manage",
      "five_s.audit.review",
      "gemba.read",
      "gemba.definitions.manage",
      "gemba.walk.review",
      "schedules.read",
      "schedules.manage",
      "training.read",
      "training.catalog.manage",
      "training.curriculum.manage",
      "skills.read",
      "skills.catalog.manage",
      "skills.requirements.manage",
      "suggestions.read",
      "suggestions.manage",
      "recognition.read",
      "recognition.award",
      "projects.read",
      "projects.manage",
      "benefits.read",
      "benefits.create",
      "benefits.manage",
      "benefits.validate.ci",
      "problem_solving.view",
      "problem_solving.create",
      "problem_solving.manage",
      "problem_solving.facilitate",
      "ai.use",
      "ai.view_history",
    ],
    invitationTokenSeed: "cookieworks-qa-ci-manager-invitation-v1",
  },
  productionManager: {
    canonicalName: "production-manager",
    displayName: "Production Manager",
    description: "Operations subtree manager for production oversight.",
    scopeType: "unit_subtree" as const,
    scopeUnitKey: "operations",
    permissions: [
      "hierarchy.read",
      "memberships.read",
      "actions.read",
      "actions.create",
      "actions.update",
      "actions.assign",
      "maturity.read",
      "maturity.assess.formal",
      "maturity.review",
      "maturity.approve",
      "five_s.read",
      "five_s.standards.manage",
      "five_s.audit.perform",
      "five_s.audit.review",
      "gemba.read",
      "gemba.definitions.manage",
      "gemba.walk.perform",
      "gemba.walk.review",
      "schedules.read",
      "schedules.manage",
      "schedules.complete",
      "training.read",
      "skills.read",
      "people.capability.read",
      "suggestions.read",
      "suggestions.review",
      "suggestions.manage",
      "recognition.read",
      "recognition.award",
      "projects.read",
      "projects.manage",
      "benefits.read",
      "benefits.create",
      "benefits.manage",
      "benefits.validate.ci",
      "problem_solving.view",
      "problem_solving.create",
      "problem_solving.manage",
    ],
    invitationTokenSeed: "cookieworks-qa-production-manager-invitation-v1",
  },
  teamLeader: {
    canonicalName: "team-leader",
    displayName: "Team Leader",
    description: "Operations unit leader with limited review permissions.",
    scopeType: "unit_subtree" as const,
    scopeUnitKey: "operations",
    permissions: [
      "hierarchy.read",
      "memberships.read",
      "actions.read",
      "actions.create",
      "actions.assign",
      "maturity.read",
      "maturity.assess.self",
      "five_s.read",
      "five_s.audit.perform",
      "gemba.read",
      "gemba.walk.perform",
      "schedules.read",
      "schedules.complete",
      "training.read",
      "skills.read",
      "people.capability.read",
      "suggestions.read",
      "suggestions.review",
      "recognition.read",
      "projects.read",
      "problem_solving.view",
      "problem_solving.contribute",
    ],
    invitationTokenSeed: "cookieworks-qa-team-leader-invitation-v1",
  },
  operator: {
    canonicalName: "line-operator",
    displayName: "Operator",
    description: "Self-scoped shop-floor operator permissions.",
    scopeType: "self" as const,
    scopeUnitKey: null,
    permissions: [
      "actions.read",
      "maturity.read",
      "maturity.assess.self",
      "five_s.read",
      "five_s.audit.perform",
      "gemba.read",
      "gemba.walk.perform",
      "schedules.read",
      "training.read",
      "skills.read",
      "people.capability.read",
      "suggestions.read",
      "suggestions.submit",
      "recognition.read",
      "problem_solving.view",
      "problem_solving.contribute",
    ],
    invitationTokenSeed: "cookieworks-qa-operator-invitation-v1",
  },
  assessor: {
    canonicalName: "maturity-assessor",
    displayName: "QA / Maturity Assessor",
    description: "Formal maturity assessment and review permissions.",
    scopeType: "organisation" as const,
    scopeUnitKey: null,
    permissions: [
      "hierarchy.read",
      "memberships.read",
      "maturity.read",
      "maturity.assess.formal",
      "maturity.review",
      "attachments.read",
      "attachments.upload",
      "comments.read",
      "comments.create",
    ],
    invitationTokenSeed: "cookieworks-qa-assessor-invitation-v1",
  },
  financeValidator: {
    canonicalName: "finance-validator",
    displayName: "Finance Validator",
    description: "Least-privilege finance validation for improvement benefits.",
    scopeType: "organisation" as const,
    scopeUnitKey: null,
    permissions: [
      "hierarchy.read",
      "memberships.read",
      "benefits.read",
      "benefits.validate.finance",
      "benefits.realisation.validate",
    ],
    invitationTokenSeed: "cookieworks-qa-finance-invitation-v1",
  },
} as const;

export const QA_USER_ROLE_KEY = {
  ciManager: "ciManager",
  productionManager: "productionManager",
  teamLeader: "teamLeader",
  operator: "operator",
  assessor: "assessor",
  finance: "financeValidator",
} as const;

export const QA_HOSTED_RESET_CONFIRM_TOKEN = "DELETE_COOKIEWORKS_ONLY";

export const QA_BOOTSTRAP_EXCEPTIONS = [
  "Baseline application roles created by provision_organisation",
  "Builtin problem-solving method catalogue from provision_organisation",
  "Organisation owner role, grant, and provisioning security audit event",
  "Organisation document sequences (if provisioned)",
  "Append-only security_audit_events and business_audit_events retained for the organisation",
] as const;
