import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, posix, win32 } from "node:path";

import { describe, expect, it, vi } from "vitest";

import {
  assertDatabaseTypesCurrent,
  DATABASE_TYPES_RELATIVE_PATH,
  type GitDiffRunner,
} from "../../scripts/qa-tenant/database-types-verify";
import { assertWorkingTreeClean } from "../../scripts/qa-tenant/working-tree-verify";

function createTypesFixtureRepo(content = "export type Foo = 1;\n") {
  const repoRoot = mkdtempSync(join(tmpdir(), "qa-db-types-mock-"));
  const relativePath = DATABASE_TYPES_RELATIVE_PATH;
  const absolutePath = join(repoRoot, relativePath);
  mkdirSync(join(repoRoot, "src/platform/supabase"), { recursive: true });
  writeFileSync(absolutePath, content, "utf8");
  return { repoRoot, relativePath, absolutePath };
}

function initGitRepo(repoRoot: string) {
  execFileSync("git", ["init"], { cwd: repoRoot });
  execFileSync("git", ["config", "user.email", "qa@example.com"], {
    cwd: repoRoot,
  });
  execFileSync("git", ["config", "user.name", "QA"], { cwd: repoRoot });
}

describe("assertDatabaseTypesCurrent", () => {
  it("passes without rewriting when generated bytes are identical to original", () => {
    const content = "export type Foo = 1;\n";
    const { repoRoot, absolutePath } = createTypesFixtureRepo(content);
    const typesPath = join(repoRoot, DATABASE_TYPES_RELATIVE_PATH);
    const originalBytes = readFileSync(absolutePath);
    const runGitDiff = vi
      .fn<GitDiffRunner>()
      .mockReturnValue({ exitCode: 0, stdout: "", stderr: "" });
    const runDbTypes = vi.fn(() => {
      writeFileSync(absolutePath, content, "utf8");
    });

    expect(() =>
      assertDatabaseTypesCurrent({
        repoRoot,
        runDbTypes,
        runGitDiff,
      }),
    ).not.toThrow();

    expect(readFileSync(absolutePath).equals(originalBytes)).toBe(true);
    expect(runGitDiff).toHaveBeenCalledTimes(2);
    expect(runGitDiff).toHaveBeenNthCalledWith(1, repoRoot, typesPath);
    expect(runGitDiff).toHaveBeenNthCalledWith(2, repoRoot, typesPath);
    expect(runDbTypes).toHaveBeenCalledOnce();
  });

  it("restores original CRLF bytes when generation writes LF and semantic diff is clean", () => {
    const originalContent = "export type Foo = 1;\r\n";
    const { repoRoot, absolutePath } = createTypesFixtureRepo(originalContent);
    const originalBytes = readFileSync(absolutePath);
    const runGitDiff = vi
      .fn<GitDiffRunner>()
      .mockReturnValue({ exitCode: 0, stdout: "", stderr: "" });
    const runDbTypes = vi.fn(() => {
      writeFileSync(absolutePath, "export type Foo = 1;\n", "utf8");
    });

    expect(() =>
      assertDatabaseTypesCurrent({
        repoRoot,
        runDbTypes,
        runGitDiff,
      }),
    ).not.toThrow();

    expect(readFileSync(absolutePath).equals(originalBytes)).toBe(true);
    expect(readFileSync(absolutePath).toString("utf8")).toBe(originalContent);
  });

  it("restores original LF bytes when generation writes CRLF and semantic diff is clean", () => {
    const originalContent = "export type Foo = 1;\n";
    const { repoRoot, absolutePath } = createTypesFixtureRepo(originalContent);
    const originalBytes = readFileSync(absolutePath);
    const runGitDiff = vi
      .fn<GitDiffRunner>()
      .mockReturnValue({ exitCode: 0, stdout: "", stderr: "" });
    const runDbTypes = vi.fn(() => {
      writeFileSync(absolutePath, "export type Foo = 1;\r\n", "utf8");
    });

    expect(() =>
      assertDatabaseTypesCurrent({
        repoRoot,
        runDbTypes,
        runGitDiff,
      }),
    ).not.toThrow();

    expect(readFileSync(absolutePath).equals(originalBytes)).toBe(true);
    expect(readFileSync(absolutePath).toString("utf8")).toBe(originalContent);
  });

  it("fails on substantive generated type drift without masking changes", () => {
    const originalContent = "export type Foo = 1;\n";
    const driftedContent = "export type Foo = 2;\n";
    const { repoRoot, absolutePath } = createTypesFixtureRepo(originalContent);
    const runGitDiff = vi
      .fn<GitDiffRunner>()
      .mockReturnValueOnce({ exitCode: 0, stdout: "", stderr: "" })
      .mockReturnValueOnce({
        exitCode: 1,
        stdout: "diff --git a/src/platform/supabase/database.types.ts",
        stderr: "",
      });
    const runDbTypes = vi.fn(() => {
      writeFileSync(absolutePath, driftedContent, "utf8");
    });

    expect(() =>
      assertDatabaseTypesCurrent({
        repoRoot,
        runDbTypes,
        runGitDiff,
      }),
    ).toThrow(
      "Generated database.types.ts differs from HEAD after db:types (schema/type drift).",
    );

    expect(readFileSync(absolutePath).toString("utf8")).toBe(driftedContent);
  });

  it("fails clearly when database.types.ts is dirty before generation", () => {
    const { repoRoot } = createTypesFixtureRepo();
    const typesPath = join(repoRoot, DATABASE_TYPES_RELATIVE_PATH);
    const runGitDiff = vi.fn<GitDiffRunner>().mockReturnValueOnce({
      exitCode: 1,
      stdout: "diff --git a/src/platform/supabase/database.types.ts",
      stderr: "",
    });
    const runDbTypes = vi.fn();

    expect(() =>
      assertDatabaseTypesCurrent({
        repoRoot,
        runDbTypes,
        runGitDiff,
      }),
    ).toThrow(
      "database.types.ts has uncommitted changes before db:types. Commit or revert local edits before running clean-rebuild verification.",
    );

    expect(runGitDiff).toHaveBeenCalledWith(repoRoot, typesPath);
    expect(runDbTypes).not.toHaveBeenCalled();
  });

  it("restores original bytes when ordinary git diff is clean but bytes differ (Windows autocrlf)", () => {
    const repoRoot = mkdtempSync(join(tmpdir(), "qa-db-types-win-autocrlf-"));
    const relativePath = DATABASE_TYPES_RELATIVE_PATH;
    const absolutePath = join(repoRoot, relativePath);
    mkdirSync(join(repoRoot, "src/platform/supabase"), { recursive: true });

    initGitRepo(repoRoot);
    execFileSync("git", ["config", "core.autocrlf", "true"], {
      cwd: repoRoot,
    });

    const originalContent = "export type Foo = 1;\n";
    writeFileSync(absolutePath, originalContent, "utf8");
    execFileSync("git", ["add", relativePath], { cwd: repoRoot });
    execFileSync("git", ["commit", "-m", "baseline"], { cwd: repoRoot });

    const originalBytes = readFileSync(absolutePath);

    const ordinaryGitDiff = vi.fn((root: string, filePath: string) => {
      try {
        const stdout = execFileSync(
          "git",
          ["diff", "--exit-code", "--", filePath],
          {
            cwd: root,
            encoding: "utf8",
            stdio: ["ignore", "pipe", "pipe"],
          },
        );
        return { exitCode: 0, stdout, stderr: "" };
      } catch (error) {
        const execError = error as Error & {
          status?: number;
          stdout?: string;
          stderr?: string;
        };
        return {
          exitCode: execError.status ?? 1,
          stdout: execError.stdout ?? "",
          stderr: execError.stderr ?? "",
        };
      }
    });

    const runGitDiff = vi.fn<GitDiffRunner>((_root, _filePath) => {
      return {
        exitCode: 0,
        stdout: "",
        stderr: "",
      };
    });

    const runDbTypes = vi.fn(() => {
      writeFileSync(absolutePath, "export type Foo = 1;\r\n", "utf8");
    });

    expect(readFileSync(absolutePath).equals(originalBytes)).toBe(true);

    assertDatabaseTypesCurrent({
      repoRoot,
      runDbTypes,
      runGitDiff,
    });

    expect(readFileSync(absolutePath).equals(originalBytes)).toBe(true);
    expect(readFileSync(absolutePath).toString("utf8")).toBe(originalContent);

    writeFileSync(absolutePath, "export type Foo = 1;\r\n", "utf8");
    const ordinaryDiffBeforeRestoreWouldHaveSkipped = ordinaryGitDiff(
      repoRoot,
      absolutePath,
    );
    expect(ordinaryDiffBeforeRestoreWouldHaveSkipped.exitCode).toBe(0);
    expect(readFileSync(absolutePath).equals(originalBytes)).toBe(false);
  });
});

describe("Windows path joining", () => {
  it("uses platform-aware path for database.types.ts on Windows", () => {
    const expectedPath = win32.join("D:\\repo", DATABASE_TYPES_RELATIVE_PATH);

    expect(expectedPath).toBe(
      "D:\\repo\\src\\platform\\supabase\\database.types.ts",
    );
    expect(expectedPath).not.toBe(
      "/repo/src/platform/supabase/database.types.ts",
    );
  });

  it("uses platform-aware path for database.types.ts on POSIX", () => {
    const expectedPath = posix.join("/repo", DATABASE_TYPES_RELATIVE_PATH);

    expect(expectedPath).toBe("/repo/src/platform/supabase/database.types.ts");
  });
});

describe("assertWorkingTreeClean", () => {
  it("passes when git status is empty", () => {
    expect(() => assertWorkingTreeClean("/repo", () => "")).not.toThrow();
  });

  it("fails when git status shows modifications", () => {
    expect(() =>
      assertWorkingTreeClean("/repo", () => " M next-env.d.ts"),
    ).toThrow("Working tree is not clean after verification");
  });
});

describe("defaultGitDiff EOL semantics", () => {
  it("treats CRLF-only changes as no drift with --ignore-space-at-eol", () => {
    const repoRoot = mkdtempSync(join(tmpdir(), "qa-db-types-"));
    const relativePath = DATABASE_TYPES_RELATIVE_PATH;
    const absolutePath = join(repoRoot, relativePath);
    mkdirSync(join(repoRoot, "src/platform/supabase"), { recursive: true });

    initGitRepo(repoRoot);

    writeFileSync(absolutePath, "export type Foo = 1;\n", "utf8");
    execFileSync("git", ["add", relativePath], { cwd: repoRoot });
    execFileSync("git", ["commit", "-m", "baseline"], { cwd: repoRoot });

    const originalBytes = readFileSync(absolutePath);

    expect(() =>
      assertDatabaseTypesCurrent({
        repoRoot,
        runDbTypes: () => {
          writeFileSync(absolutePath, "export type Foo = 1;\r\n", "utf8");
        },
      }),
    ).not.toThrow();

    expect(readFileSync(absolutePath).equals(originalBytes)).toBe(true);
  });

  it("fails on substantive type changes after generation", () => {
    const repoRoot = mkdtempSync(join(tmpdir(), "qa-db-types-"));
    const relativePath = DATABASE_TYPES_RELATIVE_PATH;
    const absolutePath = join(repoRoot, relativePath);
    mkdirSync(join(repoRoot, "src/platform/supabase"), { recursive: true });

    initGitRepo(repoRoot);

    writeFileSync(absolutePath, "export type Foo = 1;\n", "utf8");
    execFileSync("git", ["add", relativePath], { cwd: repoRoot });
    execFileSync("git", ["commit", "-m", "baseline"], { cwd: repoRoot });

    expect(() =>
      assertDatabaseTypesCurrent({
        repoRoot,
        runDbTypes: () => {
          writeFileSync(absolutePath, "export type Foo = 2;\n", "utf8");
        },
      }),
    ).toThrow(
      "Generated database.types.ts differs from HEAD after db:types (schema/type drift).",
    );
  });
});
